insert into organization (org_id, org_name) values (1, 'JP Morgan Chase & Co. New York NY');
insert into organization (org_id, org_name) values (2, 'Bank of America Charlotte NC');
insert into organization (org_id, org_name) values (3, 'Wells Fargo San Francisco CA');
insert into organization (org_id, org_name) values (4, 'Citigroup New York NY');
insert into organization (org_id, org_name) values (5, 'PNC Financial Services Group Pittsburgh PA');
insert into organization (org_id, org_name) values (6, 'HSBC Holdings London');
insert into organization (org_id, org_name) values (7, 'Bank of New York Mellon New York NY');
insert into organization (org_id, org_name) values (8, 'U.S. Bancorp Minneapolis MN');
insert into organization (org_id, org_name) values (9, 'SunTrust Bank Atlanta GA');
insert into organization (org_id, org_name) values (10, 'State Street Corp. Boston MA');
insert into organization (org_id, org_name) values (11, 'Capital One Financial McClean VA');
insert into organization (org_id, org_name) values (12, 'BB&T Corporation Winston-Salem NC');
insert into organization (org_id, org_name) values (13, 'Toronto-Dominion Bank Toronto ON');
insert into organization (org_id, org_name) values (14, 'Royal Bank of Scotland Edinburgh');
insert into organization (org_id, org_name) values (15, 'Regions Financial Birmingham AL');
insert into organization (org_id, org_name) values (16, 'Fifth Third Bancorp Cincinnati OH');
insert into organization (org_id, org_name) values (17, 'ING Group Wilmington DE');
insert into organization (org_id, org_name) values (18, 'KeyCorp Cleveland OH');
insert into organization (org_id, org_name) values (19, 'Northern Trust Chicago IL');
insert into organization (org_id, org_name) values (20, 'Bank of Montreal Toronto ON');
insert into organization (org_id, org_name) values (21, 'BNP Paribas (Bank of the West) Paris');
insert into organization (org_id, org_name) values (22, 'Mitsubishi UFJ Financial Group (Union Bank) Tokyo');
insert into organization (org_id, org_name) values (23, 'Allied Irish Banks Dublin');
insert into organization (org_id, org_name) values (24, 'Comerica Dallas TX');
insert into organization (org_id, org_name) values (25, 'Zions Bancorp Salt Lake City UT');
insert into organization (org_id, org_name) values (26, 'Marshall & Ilsley Milwaukee WI');
insert into organization (org_id, org_name) values (27, 'Banco Bilbao Vizcaya Argentaria S.A. Bilbao Spain');
insert into organization (org_id, org_name) values (28, 'Huntington Bancshares Columbus OH');
insert into organization (org_id, org_name) values (29, 'E-Trade Financial New York');
insert into organization (org_id, org_name) values (30, 'Synovus Financial Corp. Columbus GA');
insert into organization (org_id, org_name) values (31, 'Popular Inc. San Juan PR');
insert into organization (org_id, org_name) values (32, 'Navy Federal Credit Union Vienna VA');
insert into organization (org_id, org_name) values (33, 'Charles Schwab Corp. San Francisco CA');
insert into organization (org_id, org_name) values (34, 'Royal Bank of Canada (Centura) Toronto ON');
insert into organization (org_id, org_name) values (35, 'Colonial BancGroup Inc. Montgomery AL');
insert into organization (org_id, org_name) values (36, 'Hudson City Bancorp Paramus NJ');
insert into organization (org_id, org_name) values (37, 'Deutsche Bank Frankfurt');
insert into organization (org_id, org_name) values (38, 'People’s United Financial Inc. Bridgeport CT');
insert into organization (org_id, org_name) values (39, 'State Employees Credit Union Raleigh NC');
insert into organization (org_id, org_name) values (40, 'Associated Banc-Corp  Green Bay WI');
insert into organization (org_id, org_name) values (41, 'BOK Financial Corp. Tulsa OK');
insert into organization (org_id, org_name) values (42, 'New York Community Bancorp Inc. Westbury NY');
insert into organization (org_id, org_name) values (43, 'First Horizon National Bancorp Memphi TN');
insert into organization (org_id, org_name) values (44, 'First Citizens Bancshares Raleigh NC');
insert into organization (org_id, org_name) values (45, 'Astoria Financial Corp. Lake Success NY');
insert into organization (org_id, org_name) values (46, 'First Bancorp San Juan PR');
insert into organization (org_id, org_name) values (47, 'Commerce Bancshares Kansas City MO');
insert into organization (org_id, org_name) values (48, 'City National Bank Beverly Hills CA');
insert into organization (org_id, org_name) values (49, 'Webster Financial Corp Waterbury CT');
insert into organization (org_id, org_name) values (50, 'FBOP Corp Oak Park IL');
insert into organization (org_id, org_name) values (51, 'Cullen/Frost Bankers Inc. San Antonio TX');
insert into organization (org_id, org_name) values (52, 'Guaranty Financial Group Inc. Austin TX');
insert into organization (org_id, org_name) values (53, 'AmTrust Financial Corp. Cleveland OH');
insert into organization (org_id, org_name) values (54, 'New York Private Bank & Trust Corp New York NY');
insert into organization (org_id, org_name) values (55, 'W Holding Co. Inc. Mayaguez PR');
insert into organization (org_id, org_name) values (56, 'Fulton Financial Corp. Lancaster PA');
insert into organization (org_id, org_name) values (57, 'Pentagon Federal Credit Union Alexandria VA');
insert into organization (org_id, org_name) values (58, 'TCF Financial Wayzata MN');
insert into organization (org_id, org_name) values (59, 'Lehman Brothers Holdings Inc. New York');
insert into organization (org_id, org_name) values (60, 'Bancorpsouth Inc. Tupelo MS');
insert into organization (org_id, org_name) values (61, 'Valley National Bank Wayne NJ');
insert into organization (org_id, org_name) values (62, 'South Financial Group Greenville SC');
insert into organization (org_id, org_name) values (63, 'Whitney Holding Corp. New Orleans LA');
insert into organization (org_id, org_name) values (64, 'Susquehanna Bancshares Inc. Lititz PA');
insert into organization (org_id, org_name) values (65, 'Citizens Republic Bancorp Inc. Flint MI');
insert into organization (org_id, org_name) values (66, 'UCBH Holdings Inc. San Francisco CA');
insert into organization (org_id, org_name) values (67, 'Raymond James Financial Inc. St. Petersburg FL');
insert into organization (org_id, org_name) values (68, 'First Banks Inc. Clayton MO');
insert into organization (org_id, org_name) values (69, 'Wilmington Trust Wilmington DE');
insert into organization (org_id, org_name) values (70, 'BankUnited Financial Corp. Coral Gables FL');
insert into organization (org_id, org_name) values (71, 'Third Federal S&L Cleveland OH');
insert into organization (org_id, org_name) values (72, 'Wintrust Financial Corp Lake Forest IL');
insert into organization (org_id, org_name) values (73, 'Sterling Financial Corp. Spokane WA');
insert into organization (org_id, org_name) values (74, 'Bank of Hawaii Honolulu HI');
insert into organization (org_id, org_name) values (75, 'Arvest Bank Group Bentonville AR');
insert into organization (org_id, org_name) values (76, 'East West Bancorp Inc. Pasadena CA');
insert into organization (org_id, org_name) values (77, 'FirstBank Holding Co. Lakewood CO');
insert into organization (org_id, org_name) values (78, 'PrivateBancorp Chicago IL');
insert into organization (org_id, org_name) values (79, 'Flagstar Bancorp Inc. Troy MI');
insert into organization (org_id, org_name) values (80, 'Boeing Employees Credit Union Tukwila WA');
insert into organization (org_id, org_name) values (81, 'UMB Financial Corp. Kansas City MO');
insert into organization (org_id, org_name) values (82, 'Midland Financial Oklahoma City OK');
insert into organization (org_id, org_name) values (83, 'Firstmerit Corp. Akron OH');
insert into organization (org_id, org_name) values (84, 'Corus Bancshares Inc. Chicago IL');
insert into organization (org_id, org_name) values (85, 'SVB Financial Group Santa Clara CA');
insert into organization (org_id, org_name) values (86, 'Prosperity Bancshares Inc. Houston TX');
insert into organization (org_id, org_name) values (87, 'Washington Federal Inc. Seattle WA');
insert into organization (org_id, org_name) values (88, 'United Community Banks Inc. Blairsville GA');
insert into organization (org_id, org_name) values (89, 'MetLife Inc. New York NY');
insert into organization (org_id, org_name) values (90, 'International Bankshares Corp Laredo TX');
insert into organization (org_id, org_name) values (91, 'Cathay General Bancorp El Monte CA');
insert into organization (org_id, org_name) values (92, 'Trustmark Corp. Jackson MS');
insert into organization (org_id, org_name) values (93, 'Central Bancompany Jefferson City MO');
insert into organization (org_id, org_name) values (94, 'Umpqua Holdings Corp. Portland OR');
insert into organization (org_id, org_name) values (95, 'Pacific Capital Bancorp Santa Barbara CA');
insert into organization (org_id, org_name) values (96, 'SchoolsFirst Federal Credit Union Santa Ana CA');
insert into organization (org_id, org_name) values (97, 'MB Financial Inc. Chicago IL');
insert into organization (org_id, org_name) values (98, 'National Penn Bancshares Inc.  Boyertown PA');
insert into organization (org_id, org_name) values (99, 'Cam-Discount Ltd. Grand Cayman');
insert into organization (org_id, org_name) values (100, 'Apple Financial Holdings Inc. New York NY');
insert into organization (org_id, org_name) values (101, 'F.N.B. Corp Hermitage PA');
insert into organization (org_id, org_name) values (102, 'First Niagara Financial Lockport NY');
insert into organization (org_id, org_name) values (103, 'Golden 1 Credit Union Sacramento CA');
insert into organization (org_id, org_name) values (104, 'Hancock Holding Company Gulfport MS');
insert into organization (org_id, org_name) values (105, 'First Citizens Bancorp Inc. Columbia SC');
insert into organization (org_id, org_name) values (106, 'United Bancshares Inc. Charleston WV');
insert into organization (org_id, org_name) values (107, 'First Midwest Bancorp Inc. Itasca IL');
insert into organization (org_id, org_name) values (108, 'Old National Bancorp Evansville IN');
insert into organization (org_id, org_name) values (109, 'Otto Bremer Foundation St. Paul MN');
insert into organization (org_id, org_name) values (110, 'First Interstate Bank Billings MT');
insert into organization (org_id, org_name) values (111, 'Northwest Bancorp MHC Warren PA');
insert into organization (org_id, org_name) values (112, 'Eastern Bank Corp. Boston MA');
insert into organization (org_id, org_name) values (113, 'Suncoast Schools Federal Credit Union  Tampa FL');
insert into organization (org_id, org_name) values (114, 'Banco Santander Santander Spain');
insert into organization (org_id, org_name) values (115, 'EverBank Financial Corp. Jacksonville FL');
insert into organization (org_id, org_name) values (116, 'Dickinson Financial Corp. Kansas City MO');
insert into organization (org_id, org_name) values (117, 'Boston Private Financial Holdings Inc. Boston MA');
insert into organization (org_id, org_name) values (118, 'FirstFed Financial Corp. Los Angeles CA');
insert into organization (org_id, org_name) values (119, 'Bank Leumi Ie-Israel BM Tel-Aviv Israel');
insert into organization (org_id, org_name) values (120, 'American Airlines Federal Credit Union Fort Worth TX');
insert into organization (org_id, org_name) values (121, 'Rabobank Nederland Utrecht');
insert into organization (org_id, org_name) values (122, 'Park National Corp. Newark OH');
insert into organization (org_id, org_name) values (123, 'Provident Bancshares Baltimore MD');
insert into organization (org_id, org_name) values (124, 'Alliant Credit Union Chicago IL');
insert into organization (org_id, org_name) values (125, 'Capitol Bancorp Ltd. Lansing MI');
insert into organization (org_id, org_name) values (126, 'NewAlliance Bancshares Inc New Haven CT');
insert into organization (org_id, org_name) values (127, 'Johnson Financial Group Racine WI');
insert into organization (org_id, org_name) values (128, 'R&G Financial Corp. Hato Rey PR');
insert into organization (org_id, org_name) values (129, 'Doral Financial Corp San Juan Puerto Rico');
insert into organization (org_id, org_name) values (130, 'Mercantil Servicios Financieros Caracas');
insert into organization (org_id, org_name) values (131, 'First Commonwealth Financial Corporation Indiana PA');
insert into organization (org_id, org_name) values (132, 'Pinnacle Bancorp Inc.  Central City NE');
insert into organization (org_id, org_name) values (133, 'Investors Bancorp MHC Short Hills NJ');
insert into organization (org_id, org_name) values (134, 'Provident Financial Services Inc. Jersey City NJ');
insert into organization (org_id, org_name) values (135, 'Ocean Bankshares Inc. Miami FL');
insert into organization (org_id, org_name) values (136, 'Security Service Federal Credit Union San Antonio TX');
insert into organization (org_id, org_name) values (137, 'Capitol Federal Savings Bank MHC Topeka KS');
insert into organization (org_id, org_name) values (138, 'Iberiabank Corp. Lafayette LA');
insert into organization (org_id, org_name) values (139, 'SNBNY Holdings Gibraltar');
insert into organization (org_id, org_name) values (140, 'San Diego County Credit Union San Diego CA');
insert into organization (org_id, org_name) values (141, 'America First Federal Credit Union Riverdale UT');
insert into organization (org_id, org_name) values (142, 'Harleysville National Corp. Harleysville PA');
insert into organization (org_id, org_name) values (143, 'BFC Financial Corp Fort Lauderdale FL');
insert into organization (org_id, org_name) values (144, 'Amcore Financial Inc. Rockford IL');
insert into organization (org_id, org_name) values (145, 'NBT Bancorp Inc. Norwich NY');
insert into organization (org_id, org_name) values (146, 'Central Pacific Financial Corp. Honolulu HI');
insert into organization (org_id, org_name) values (147, 'Sterling Bancshares Houston TX');
insert into organization (org_id, org_name) values (148, 'Banner Corp. Walla Walla WA');
insert into organization (org_id, org_name) values (149, 'First Merchants Corp Muncie IN');
insert into organization (org_id, org_name) values (150, 'Community Bank System De Witt NY');